Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,47 +1,46 @@
 name: CI with Docker
 
 on:
-  push:
-  pull_request:
-    branches: [ main ]
+  push:
+  pull_request:
+    branches: [ main ]
 
 jobs:
-  test:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-      - name: Set up Python
-        uses: actions/setup-python@v3
-        with:
-          python-version: "3.12"
+      - name: Set up Python
+        uses: actions/setup-python@v3
+        with:
+          python-version: "3.12"
 
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
 
-      - name: Build and run services
-        run: |
-          docker-compose -f docker-compose.yml up --build -d
+      - name: Build and run services
+        run: |
+          docker-compose -f docker-compose-test.yml up --build -d
 
-      - name: Wait for services to be healthy 
-        run: |
-          echo "Waiting for app service to become healthy..."
-          RETRIES=30
-          until [ $(docker inspect --format='{{.State.Health.Status}}' $(docker-compose -f docker-compose-test.yml ps -q app)) == 'healthy' ] || [ $RETRIES -eq 0 ]; do
-            echo -n "."
-            sleep 5
-            RETRIES=$(($RETRIES-1))
-          done
-          if [ $RETRIES -eq 0 ]; then
-            echo "App service failed to become healthy."
-            exit 1
-          fi
-          echo "App is healthy."
+      - name: Wait for services to be healthy
+        run: |
+          echo "Waiting for app service to become healthy..."
+          RETRIES=30
+          until [ $(docker inspect --format='{{.State.Health.Status}}' $(docker-compose -f docker-compose-test.yml ps -q app)) == 'healthy' ] || [ $RETRIES -eq 0 ]; do
+            echo -n "."
+            sleep 5
+            RETRIES=$(($RETRIES-1))
+          done
+          if [ $RETRIES -eq 0 ]; then
+            echo "App service failed to become healthy."
+            exit 1
+          fi
+          echo "App is healthy."
 
-
-      - name: Run tests
-        run: |
-          docker-compose -f docker-compose.yml exec app pytest tests
+      - name: Run tests
+        run: |
+          docker-compose -f docker-compose-test.yml exec app pytest tests
